# -*- coding: utf-8 -*-
"""Blackjack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JkKS5YfPMfnnurJTnC8DUABs9U3HcSLt
"""

import random

class Card:
    def __init__(self, suit, rank):
        self.suit = suit
        self.rank = rank

    def get_symbol(self):
        symbols = {"spades": "♠", "clubs": "♣", "hearts": "♥", "diamonds": "♦"}
        return symbols.get(self.suit, "")

class Deck:
    def __init__(self):
        self.cards = []
        suits = ["spades", "clubs", "hearts", "diamonds"]
        ranks = [
            {"rank": "A", "value": 11},
            {"rank": "2", "value": 2},
            {"rank": "3", "value": 3},
            {"rank": "4", "value": 4},
            {"rank": "5", "value": 5},
            {"rank": "6", "value": 6},
            {"rank": "7", "value": 7},
            {"rank": "8", "value": 8},
            {"rank": "9", "value": 9},
            {"rank": "10", "value": 10},
            {"rank": "J", "value": 10},
            {"rank": "Q", "value": 10},
            {"rank": "K", "value": 10},
        ]
        for suit in suits:
            for rank in ranks:
                self.cards.append(Card(suit, rank))

    def shuffle(self):
        if len(self.cards) > 1:
            random.shuffle(self.cards)

    def deal(self, number=1):
        cards_dealt = []
        for _ in range(number):
            if len(self.cards) > 0:
                cards_dealt.append(self.cards.pop())
        return cards_dealt

class Hand:
    def __init__(self, dealer=False):
        self.cards = []
        self.value = 0
        self.dealer = dealer

    def add_card(self, card_list):
        self.cards.extend(card_list)

    def calculate_value(self):
        self.value = 0
        has_ace = False

        for card in self.cards:
            card_value = int(card.rank["value"])
            self.value += card_value
            if card.rank["rank"] == "A":
                has_ace = True

        if has_ace and self.value > 21:
            self.value -= 10

    def get_value(self):
        self.calculate_value()
        return self.value

    def is_blackjack(self):
        return self.get_value() == 21 and len(self.cards) == 2

    def display(self, show_all_dealer_cards=False):
        title = "👑 DEALER'S HAND" if self.dealer else "👤 YOUR HAND"
        print(f"\n{title}")

        cards_to_show = []
        for index, card in enumerate(self.cards):
            if index == 0 and self.dealer and not show_all_dealer_cards and not self.is_blackjack():
                cards_to_show.append("HIDDEN")
            else:
                cards_to_show.append(card)

        top = ""
        mid_rank = ""
        mid_suit = ""
        bot = ""

        for c in cards_to_show:
            if c == "HIDDEN":
                top += "┌───────┐ "
                mid_rank += "│ ░░░░░ │ "
                mid_suit += "│ ░░░░░ │ "
                bot += "└───────┘ "
            else:
                r = c.rank["rank"]
                s = c.get_symbol()
                rank_str = f"{r:<2}"
                top += "┌───────┐ "
                mid_rank += f"│ {rank_str}    │ "
                mid_suit += f"│   {s}   │ "
                bot += "└───────┘ "

        print(top)
        print(mid_rank)
        print(mid_suit)
        print(bot)

        if not self.dealer:
            print(f"Total Value: {self.get_value()}")
        elif show_all_dealer_cards:
            print(f"Total Value: {self.get_value()}")

class Game:
    def play(self):
        print("=" * 40)
        print("          🎰 BLACKJACK 21 🎰          ")
        print("=" * 40)

        game_number = 0
        games_to_play = 0

        while games_to_play <= 0:
            try:
                games_to_play = int(input("How many games do you want to play?: "))
            except ValueError:
                print("Please enter a valid number.")

        while game_number < games_to_play:
            game_number += 1

            deck = Deck()
            deck.shuffle()

            player_hand = Hand()
            dealer_hand = Hand(dealer=True)

            player_hand.add_card(deck.deal(2))
            dealer_hand.add_card(deck.deal(2))

            print("\n" + "─" * 40)
            print(f"ROUND {game_number} OF {games_to_play}")
            print("─" * 40)

            player_hand.display()
            dealer_hand.display()

            if self.check_winner(player_hand, dealer_hand):
                continue

            choice = ""
            while choice not in ["s", "stand"] and player_hand.get_value() < 21:
                choice = input("\nChoose [H]it or [S]tand: ").lower().strip()
                while choice not in ["h", "s", "hit", "stand"]:
                    choice = input("Invalid option. Choose [H]it or [S]tand: ").lower().strip()

                if choice in ["hit", "h"]:
                    player_hand.add_card(deck.deal(1))
                    player_hand.display()
                    dealer_hand.display()

            if player_hand.get_value() > 21:
                self.check_winner(player_hand, dealer_hand)
                continue

            dealer_hand_value = dealer_hand.get_value()
            while dealer_hand_value < 17:
                dealer_hand.add_card(deck.deal(1))
                dealer_hand_value = dealer_hand.get_value()

            print("\n--- REVEALING DEALER HAND ---")
            player_hand.display()
            dealer_hand.display(show_all_dealer_cards=True)

            self.check_winner(player_hand, dealer_hand, game_over=True)

        print("\nThanks for playing! See you next time. 🃏\n")

    def check_winner(self, player_hand, dealer_hand, game_over=False):
        if not game_over:
            if player_hand.get_value() > 21:
                print("\n💥 You busted! Dealer wins!")
                return True
            elif dealer_hand.get_value() > 21:
                print("\n🎉 Dealer busted! You win!")
                return True
            elif player_hand.is_blackjack() and dealer_hand.is_blackjack():
                print("\n🤝 Both have Blackjack! Tie!")
                return True
            elif player_hand.is_blackjack():
                print("\n🔥 BLACKJACK! You win!")
                return True
            elif dealer_hand.is_blackjack():
                print("\n👑 Dealer has Blackjack! Dealer wins!")
                return True
        else:
            p_val = player_hand.get_value()
            d_val = dealer_hand.get_value()
            if p_val > 21:
                print("\n💥 You busted! Dealer wins!")
            elif d_val > 21:
                print("\n🎉 Dealer busted! You win!")
            elif p_val > d_val:
                print("\n🏆 You win!")
            elif p_val == d_val:
                print("\n🤝 It's a Tie!")
            else:
                print("\n😭 Dealer wins!")
            return True

        return False

g = Game()
g.play()